# Generated by Django 4.2.5 on 2023-09-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OneToOne', '0002_category_alter_maqola_options_maqola_create_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'id',
                'verbose_name_plural': 'idlar',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Turkum', 'verbose_name_plural': 'Turkumlar'},
        ),
    ]
