# Generated by Django 4.2.5 on 2023-09-26 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OneToOne', '0003_number_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='maqola',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OneToOne.category'),
        ),
        migrations.AddField(
            model_name='maqola',
            name='num',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='OneToOne.number'),
        ),
    ]
